# pessoa = input("Digite o nome da pessoa: ")
# print("Boa noite", pessoa)
# idade = input ("Qual a sua idade? ")
# print("Nossa! voce já tem", idade, "anos")
# email = input ("Qual o seu email? ")
# print("Seu email é",email)

numero = input("Digite um número: ")
outroNumero = input("Digite outro número: ")
print("A soma é", float(numero) + float(outroNumero))